"""empty message

Revision ID: 0225bfcc0777
Revises: a60d32863e1c
Create Date: 2025-12-13 21:03:27.405959

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0225bfcc0777'
down_revision = 'a60d32863e1c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('guards', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mobile', sa.String(length=15), nullable=False))
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))
        batch_op.drop_constraint(batch_op.f('guards_username_key'), type_='unique')
        batch_op.create_unique_constraint(None, ['mobile'])
        batch_op.drop_column('username')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('guards', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint(batch_op.f('guards_username_key'), ['username'], postgresql_nulls_not_distinct=False)
        batch_op.drop_column('is_active')
        batch_op.drop_column('mobile')

    # ### end Alembic commands ###
