"""empty message

Revision ID: 0f6c17f6c0e4
Revises: 1e0491a49b32
Create Date: 2025-12-17 03:46:41.447399

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f6c17f6c0e4'
down_revision = '1e0491a49b32'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gate_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gate_name', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('gate_name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('gate_status')
    # ### end Alembic commands ###
