"""empty message

Revision ID: 0fe72836e820
Revises: fc1502a95fa0
Create Date: 2026-01-25 08:06:03.228969

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0fe72836e820'
down_revision = 'fc1502a95fa0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('push_subscription',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resident_id', sa.Integer(), nullable=False),
    sa.Column('endpoint', sa.String(length=255), nullable=False),
    sa.Column('p256dh', sa.String(length=255), nullable=False),
    sa.Column('auth', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['resident_id'], ['residents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # op.drop_table('maintenance_payments')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_table('maintenance_payments',
    # sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    # sa.Column('resident_id', sa.INTEGER(), autoincrement=False, nullable=False),
    # sa.Column('flat_id', sa.INTEGER(), autoincrement=False, nullable=False),
    # sa.Column('year', sa.INTEGER(), autoincrement=False, nullable=False),
    # sa.Column('amount', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    # sa.Column('proof_image', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    # sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    # sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    # sa.Column('approved_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    # sa.Column('approved_by', sa.INTEGER(), autoincrement=False, nullable=True),
    # sa.ForeignKeyConstraint(['approved_by'], ['admins.id'], name=op.f('maintenance_payments_approved_by_fkey')),
    # sa.ForeignKeyConstraint(['flat_id'], ['flats.id'], name=op.f('maintenance_payments_flat_id_fkey')),
    # sa.ForeignKeyConstraint(['resident_id'], ['residents.id'], name=op.f('maintenance_payments_resident_id_fkey')),
    # sa.PrimaryKeyConstraint('id', name=op.f('maintenance_payments_pkey'))
    # )
    op.drop_table('push_subscription')
    # ### end Alembic commands ###
