"""Create tables

Revision ID: 4a39b8fd7306
Revises:
Create Date: 2025-10-12 17:36:38.667919

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a39b8fd7306'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flats',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fnum', sa.Integer(), nullable=False),
    sa.Column('fowner', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('guard',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('guname', sa.String(length=100), nullable=False),
    sa.Column('gpassword', sa.String(length=100), nullable=False),
    sa.Column('gmobile', sa.String(length=13), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('residents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('mobile', sa.String(length=15), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=True),
    sa.Column('flat_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['flat_id'], ['flats.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('mobile')
    )
    op.create_table('visitors',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('flat_id', sa.Integer(), nullable=False),
    sa.Column('vfowner', sa.String(length=100), nullable=True),
    sa.Column('vname', sa.String(length=100), nullable=False),
    sa.Column('vwork', sa.String(length=100), nullable=False),
    sa.Column('v_in', sa.String(length=100), nullable=True),
    sa.Column('v_out', sa.String(length=100), nullable=True),
    sa.Column('guard_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['flat_id'], ['flats.id'], ),
    sa.ForeignKeyConstraint(['guard_id'], ['guard.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('visitors')
    op.drop_table('residents')
    op.drop_table('guard')
    op.drop_table('flats')
    # ### end Alembic commands ###
