"""Initial migration

Revision ID: fed14418cc7e
Revises:
Create Date: 2025-09-06 17:55:36.357332

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fed14418cc7e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('v_reg',
    sa.Column('vsno', sa.INTEGER(), nullable=False),
    sa.Column('vfnum', sa.INTEGER(), nullable=False),
    sa.Column('vfowner', sa.VARCHAR(length=100), nullable=False),
    sa.Column('vname', sa.VARCHAR(length=100), nullable=False),
    sa.Column('vwork', sa.VARCHAR(length=100), nullable=False),
    sa.Column('v_in', sa.VARCHAR(length=100), nullable=False),
    sa.Column('v_out', sa.VARCHAR(length=100), nullable=False),
    sa.PrimaryKeyConstraint('vsno')
    )
    op.create_table('flats',
    sa.Column('fsno', sa.INTEGER(), nullable=False),
    sa.Column('fnum', sa.INTEGER(), nullable=False),
    sa.Column('fowner', sa.VARCHAR(length=100), nullable=False),
    sa.PrimaryKeyConstraint('fsno')
    )
    op.create_table('guard',
    sa.Column('gsn', sa.INTEGER(), nullable=False),
    sa.Column('guname', sa.VARCHAR(length=100), nullable=False),
    sa.Column('gpassword', sa.VARCHAR(length=100), nullable=False),
    sa.Column('gmobile', sa.VARCHAR(length=13), nullable=False),
    sa.PrimaryKeyConstraint('gsn')
    )


def downgrade():
    # ### end Alembic commands ###
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('guard')
    op.drop_table('flats')
    op.drop_table('v_reg')
    # ### end Alembic commands ###


