"""Init postgres

Revision ID: 92e326dcc076
Revises: 
Create Date: 2026-06-14 21:40:45.049837

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92e326dcc076'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('flat_number', sa.String(length=20), nullable=False),
    sa.Column('status', sa.Enum('occupied', 'vacant', name='flat_status'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('flat_number')
    )
    op.create_table('gates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('type', sa.Enum('entry_only', 'exit_only', 'both', name='gate_type'), nullable=False),
    sa.Column('status', sa.Enum('active', 'inactive', name='gate_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('visitors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('photo_url', sa.String(length=500), nullable=True),
    sa.Column('id_proof_url', sa.String(length=500), nullable=True),
    sa.Column('is_blacklisted', sa.Boolean(), nullable=False),
    sa.Column('blacklist_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('resident', 'guard', 'admin', name='user_role'), nullable=False),
    sa.Column('status', sa.Enum('active', 'inactive', 'pending_verification', name='user_status'), nullable=False),
    sa.Column('requested_flat_id', sa.Integer(), nullable=True),
    sa.Column('expo_push_token', sa.String(length=255), nullable=True),
    sa.Column('move_in_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['requested_flat_id'], ['flats.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone')
    )
    op.create_table('announcements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('priority', sa.Enum('normal', 'urgent', name='announcement_priority'), nullable=False),
    sa.Column('attachment_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('flat_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('flat_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('primary', 'spouse', 'parent', 'child', 'sibling', name='flat_user_role'), nullable=False),
    sa.Column('is_owner', sa.Boolean(), nullable=False),
    sa.Column('can_approve', sa.Boolean(), nullable=False),
    sa.Column('move_in_date', sa.Date(), nullable=False),
    sa.Column('move_out_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['flat_id'], ['flats.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('guards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.String(length=50), nullable=False),
    sa.Column('shift', sa.Enum('morning', 'night', name='guard_shift'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('maintenance_bills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('flat_id', sa.Integer(), nullable=False),
    sa.Column('bill_period', sa.String(length=20), nullable=False),
    sa.Column('schedule', sa.Enum('monthly', 'quarterly', 'half_yearly', 'yearly', name='bill_schedule'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('unpaid', 'paid', 'overdue', name='bill_status'), nullable=False),
    sa.Column('paid_by', sa.Integer(), nullable=True),
    sa.Column('amount_paid', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('payment_mode', sa.Enum('upi', 'card', 'cash', 'bank_transfer', name='payment_mode'), nullable=True),
    sa.Column('transaction_ref', sa.String(length=100), nullable=True),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('receipt_url', sa.String(length=500), nullable=True),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['flat_id'], ['flats.id'], ),
    sa.ForeignKeyConstraint(['paid_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('panic_alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('triggered_by', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('guard', 'resident', name='panic_role'), nullable=False),
    sa.Column('gate_id', sa.Integer(), nullable=True),
    sa.Column('flat_id', sa.Integer(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('active', 'resolved', name='panic_status'), nullable=False),
    sa.Column('resolved_by', sa.Integer(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['flat_id'], ['flats.id'], ),
    sa.ForeignKeyConstraint(['gate_id'], ['gates.id'], ),
    sa.ForeignKeyConstraint(['resolved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['triggered_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('frequent_passes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('flat_user_id', sa.Integer(), nullable=False),
    sa.Column('visitor_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('valid_from', sa.Date(), nullable=False),
    sa.Column('valid_until', sa.Date(), nullable=True),
    sa.Column('allowed_days', sa.String(length=50), nullable=False),
    sa.Column('allowed_from', sa.Time(), nullable=False),
    sa.Column('allowed_until', sa.Time(), nullable=False),
    sa.Column('status', sa.Enum('active', 'suspended', 'expired', name='frequent_pass_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['flat_user_id'], ['flat_users.id'], ),
    sa.ForeignKeyConstraint(['visitor_id'], ['visitors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gate_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('guard_id', sa.Integer(), nullable=False),
    sa.Column('gate_id', sa.Integer(), nullable=False),
    sa.Column('shift_start', sa.DateTime(), nullable=False),
    sa.Column('shift_end', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['gate_id'], ['gates.id'], ),
    sa.ForeignKeyConstraint(['guard_id'], ['guards.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pre_approvals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('flat_user_id', sa.Integer(), nullable=False),
    sa.Column('visitor_name', sa.String(length=150), nullable=False),
    sa.Column('visitor_phone', sa.String(length=20), nullable=False),
    sa.Column('valid_from', sa.DateTime(), nullable=False),
    sa.Column('valid_until', sa.DateTime(), nullable=False),
    sa.Column('purpose', sa.String(length=200), nullable=True),
    sa.Column('is_recurring', sa.Boolean(), nullable=False),
    sa.Column('recurrence_rule', sa.String(length=50), nullable=True),
    sa.Column('used_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('active', 'expired', 'cancelled', name='pre_approval_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['flat_user_id'], ['flat_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('visitor_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('visitor_id', sa.Integer(), nullable=False),
    sa.Column('flat_id', sa.Integer(), nullable=False),
    sa.Column('flat_user_id', sa.Integer(), nullable=False),
    sa.Column('entry_gate_id', sa.Integer(), nullable=False),
    sa.Column('entry_mode', sa.Enum('foot', 'two_wheeler', 'four_wheeler', name='entry_mode'), nullable=False),
    sa.Column('vehicle_number', sa.String(length=20), nullable=True),
    sa.Column('entered_at', sa.DateTime(), nullable=True),
    sa.Column('registered_by_guard', sa.Integer(), nullable=True),
    sa.Column('approval_source', sa.Enum('guard_initiated', 'self_checkin', name='approval_source'), nullable=False),
    sa.Column('approval_status', sa.Enum('pending', 'approved', 'denied', name='approval_status'), nullable=False),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('purpose', sa.String(length=100), nullable=False),
    sa.Column('stay_duration', sa.Enum('30min', '1_2hr', 'half_day', 'full_day', 'overnight', name='stay_duration'), nullable=False),
    sa.Column('expected_exit_by', sa.DateTime(), nullable=True),
    sa.Column('expected_exit_gate_id', sa.Integer(), nullable=True),
    sa.Column('actual_exit_gate_id', sa.Integer(), nullable=True),
    sa.Column('actual_exit_at', sa.DateTime(), nullable=True),
    sa.Column('exit_confirmed_by', sa.Enum('guard', 'resident', 'system', name='exit_confirmed_by'), nullable=True),
    sa.Column('status', sa.Enum('pending', 'approved', 'denied', 'inside', 'overdue', 'exited', 'unconfirmed_exit', 'cancelled', name='visitor_log_status'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['actual_exit_gate_id'], ['gates.id'], ),
    sa.ForeignKeyConstraint(['approved_by'], ['flat_users.id'], ),
    sa.ForeignKeyConstraint(['entry_gate_id'], ['gates.id'], ),
    sa.ForeignKeyConstraint(['expected_exit_gate_id'], ['gates.id'], ),
    sa.ForeignKeyConstraint(['flat_id'], ['flats.id'], ),
    sa.ForeignKeyConstraint(['flat_user_id'], ['flat_users.id'], ),
    sa.ForeignKeyConstraint(['registered_by_guard'], ['guards.id'], ),
    sa.ForeignKeyConstraint(['visitor_id'], ['visitors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('visitor_log_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.Enum('approval_request', 'overdue_alert', 'entry_confirmed', 'exit_confirmed', 'pre_approval_used', 'departure_confirmation', 'panic_alert', 'announcement', 'bill_due', name='notification_type'), nullable=False),
    sa.Column('channel', sa.Enum('push', 'sms', 'in_app', name='notification_channel'), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('sent', 'delivered', 'failed', name='notification_status'), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['visitor_log_id'], ['visitor_logs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('visitor_ratings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('visitor_log_id', sa.Integer(), nullable=False),
    sa.Column('rated_by', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['rated_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['visitor_log_id'], ['visitor_logs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('visitor_ratings')
    op.drop_table('notifications')
    op.drop_table('visitor_logs')
    op.drop_table('pre_approvals')
    op.drop_table('gate_sessions')
    op.drop_table('frequent_passes')
    op.drop_table('panic_alerts')
    op.drop_table('maintenance_bills')
    op.drop_table('guards')
    op.drop_table('flat_users')
    op.drop_table('announcements')
    op.drop_table('users')
    op.drop_table('visitors')
    op.drop_table('gates')
    op.drop_table('flats')
    # ### end Alembic commands ###
