"""Add maintenance subscriptions

Revision ID: de133dcac7da
Revises: 92e326dcc076
Create Date: 2026-06-17 16:40:52.297430

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de133dcac7da'
down_revision: Union[str, None] = '92e326dcc076'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('maintenance_payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('flat_id', sa.Integer(), nullable=False),
    sa.Column('paid_by', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('months_added', sa.Integer(), nullable=False),
    sa.Column('utr_number', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', name='maint_payment_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['flat_id'], ['flats.id'], ),
    sa.ForeignKeyConstraint(['paid_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('flats', sa.Column('maintenance_valid_until', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('flats', 'maintenance_valid_until')
    op.drop_table('maintenance_payments')
    # ### end Alembic commands ###
